### ISSUE TITLE
Compatibility with NODEMCU (ESP8266)

### ISSUE THREAD

**Issue by TheChapu** [sparkfun/SparkFun_HTU21D_Breakout_Arduino_Library#6]
Can you provide a sample code for Nodemcu?

Thank you so much

**Comment by bboyho** [comment]
HI,

I just noticed your request when browsing our GitHub issues. I have not used the NodeMCU specifically in projects and I do not have the HTU21D at the moment due to the board being retired. However, you should look at the tutorial linked below that I found on Hackster.io for an idea if you are still looking. Under **Code** there is a tab called **NodeMCU Webserver with Si7021** what has the Arduino example using development board and sensor. While it uses the Si7021, it should work for the HTU21D. The Si7021 is a drop-in replacement for the HTU21D. The address and methods are the same when communicating with the sensors. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Hackster.io: Sensor Network with NodeMCU and si7021 Sensor](https://www.hackster.io/shaddow1201/sensor-network-with-nodemcu-and-si7021-sensor-46fc4f?f=1)
